### ISSUE TITLE
build with aeson-2.0 fails

### ISSUE THREAD

**Issue by juhp** [eggzilla/Taxonomy#4]
```
Taxonomy                       > /tmp/stack-f003890b357ae714/Taxonomy-2.2.0/Biobase/Taxonomy/Types.hs:296:53: error:
Taxonomy                       >     • Couldn't match expected type ‘A.Key’ with actual type ‘T.Text’
Taxonomy                       >     • In the first argument of ‘(A..=)’, namely ‘T.pack "children"’
Taxonomy                       >       In the expression: T.pack "children" A..= children
Taxonomy                       >       In the first argument of ‘A.object’, namely
Taxonomy                       >         ‘[currentScientificName, T.pack "children" A..= children]’
Taxonomy                       >     |
Taxonomy                       > 296 |   where jsonValue = A.object [currentScientificName,T.pack "children" A..= children]
Taxonomy                       >     |                                                     ^^^^^^^^^^^^^^^^^
Taxonomy                       > 
Taxonomy                       > /tmp/stack-f003890b357ae714/Taxonomy-2.2.0/Biobase/Taxonomy/Types.hs:299:33: error:
Taxonomy                       >     • Couldn't match expected type ‘A.Key’ with actual type ‘T.Text’
Taxonomy                       >     • In the first argument of ‘(A..=)’, namely ‘T.pack "name"’
Taxonomy                       >       In the expression:
Taxonomy                       >         T.pack "name"
Taxonomy                       >           A..=
Taxonomy                       >             maybe
Taxonomy                       >               (T.pack "notFound") (TL.toStrict . simpleScientificName)
Taxonomy                       >               currentLabel
Taxonomy                       >       In an equation for ‘currentScientificName’:
Taxonomy                       >           currentScientificName
Taxonomy                       >             = T.pack "name"
Taxonomy                       >                 A..=
Taxonomy                       >                   maybe
Taxonomy                       >                     (T.pack "notFound") (TL.toStrict . simpleScientificName)
Taxonomy                       >                     currentLabel
Taxonomy                       >     |
Taxonomy                       > 299 |         currentScientificName = T.pack "name" A..= maybe (T.pack "notFound") (TL.toStrict  . simpleScientificName) currentLabel
Taxonomy                       >     |                                 ^^^^^^^^^^^^^
```
